# Generated by Django 3.2.7 on 2021-10-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20211004_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinate',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='lon',
            field=models.FloatField(),
        ),
    ]
