# Generated by Django 3.2.7 on 2021-10-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20211004_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='cellnumber',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
