# Generated by Django 3.2.7 on 2021-10-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_device_cellnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='descriptions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
