# Generated by Django 3.2.7 on 2021-10-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_device_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinate',
            name='z',
            field=models.FloatField(null=True),
        ),
    ]
